// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    project
    (
        init => init
        upgrade => upgrade
        getRegistrationFee => registration_fee
        getRegistrationFeeVip => registration_fee_vip
        getNormalTicketNumber => normal_ticket_number
        getVipTicketNumber => vip_ticket_number
        resaleTicketFee => resale_ticket_fee
        getResaleNormalTicketNumber => resale_normal_ticket_number
        getResaleVipTicketNumber => resale_vip_ticket_number
        getParticipants => participants
        getVipParticipants => vip_participants
        see_normal_ticket_price => see_normal_ticket_price
        see_vip_ticket_price => see_vip_ticket_price
        see_vip_ticket_number => see_vip_ticket_number
        register => register
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
