// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    my_neversea_2025
    (
        init => init
        getRegistrationFee => registration_fee
        getRegistrationFeeVip => registration_fee_vip
        getParticipants => participants
        getVipParticipants => vip_participants
        update_normal_registration_fee => update_normal_registration_fee
        update_vip_registration_fee => update_vip_registration_fee
        register => register
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
